Patient Vital Signs Monitor: src/alerts.c File Reference
alerts.c File Reference
Implementation of alert record generation from vital sign readings.
#include "alerts.h"
#include <stdio.h>
#include <string.h>
Macros
#define _CRT_SECURE_NO_WARNINGS
#define PUSH_ALERT(_al, param, fmt, ...)
Functions
int generate_alerts (const VitalSigns *vitals, Alert *out, int max_out)
Generate structured alert records for out-of-range vital signs.
Detailed Description
Implementation of alert record generation from vital sign readings.
Implements generate_alerts() declared in alerts.h. Each abnormal parameter produces exactly one Alert record written into the caller's buffer. The internal PUSH_ALERT macro encapsulates the bounds check and string formatting to keep the function body concise and auditable.
Implementation Notes
_CRT_SECURE_NO_WARNINGS suppresses MSVC deprecation warnings for strncpy and snprintf. These functions are used with explicit length limits and guaranteed null-termination, so the usage is safe.
The macro parameter is named _al (not level) to avoid shadowing the struct field Alert.level inside the macro expansion body.
Version
1.0.0
Date
2026-04-06
Author
vinu-engineer
Definition in file alerts.c.
Macro Definition Documentation
_CRT_SECURE_NO_WARNINGS
#define _CRT_SECURE_NO_WARNINGS
Definition at line 24 of file alerts.c.
PUSH_ALERT
#define PUSH_ALERT (_al, param, fmt, ...)
Value:
do {                                                                     \
    if (count < max_out) {                                               \
        out[count].level = (_al);                                        \
        strncpy(out[count].parameter, (param), 31);                      \
        out[count].parameter[31] = '\0';                                 \
        snprintf(out[count].message, ALERT_MSG_LEN, fmt, __VA_ARGS__);   \
        count++;                                                          \
    }                                                                     \
} while (0)
Referenced by generate_alerts().
Function Documentation
generate_alerts()
int generate_alerts (const VitalSigns * vitals, Alert * out, int max_out)
Generate structured alert records for out-of-range vital signs.
Generate alert records for every vital sign parameter outside its normal clinical range.
Internal flow for each parameter:
Call the corresponding check_*() function.
If the result is not ALERT_NORMAL, write an Alert record via PUSH_ALERT.
PUSH_ALERT enforces the max_out cap before writing.
The PUSH_ALERT macro copies the parameter name with strncpy (max 31 chars
null) and formats the message with snprintf (max ALERT_MSG_LEN - 1 chars
null), guaranteeing null-termination in both fields.
Definition at line 44 of file alerts.c.
References ALERT_NORMAL, check_blood_pressure(), check_heart_rate(), check_spo2(), check_temperature(), VitalSigns::diastolic_bp, VitalSigns::heart_rate, PUSH_ALERT, VitalSigns::spo2, VitalSigns::systolic_bp, and VitalSigns::temperature.
Referenced by patient_print_summary(), print_reading(), and update_dashboard().