Patient Vital Signs Monitor: include/alerts.h File Reference
alerts.h File Reference
Alert record generation from a set of vital sign measurements.
#include "vitals.h"
Classes
struct Alert
A single alert record describing one out-of-range vital sign.
Macros
#define ALERT_MSG_LEN 96
Maximum length (including null terminator) of an alert message.
#define MAX_ALERTS 5
Maximum number of alerts that can be generated from one VitalSigns.
Functions
int generate_alerts (const VitalSigns *vitals, Alert *out, int max_out)
Generate alert records for every vital sign parameter outside its normal clinical range.
Detailed Description
Alert record generation from a set of vital sign measurements.
This module is responsible for translating a VitalSigns observation into a structured list of Alert records — one per abnormal parameter. It acts as the bridge between raw clinical data (vitals.h) and the patient management layer (patient.h).
Design Decisions
Each abnormal parameter produces exactly one Alert record.
The output buffer size is controlled by the caller via max_out, making the function safe for use in memory-constrained embedded targets.
All-normal vitals produce zero alerts (return value 0).
Alert messages are human-readable and suitable for display on a clinical workstation or serial console.
IEC 62304 Traceability
Software Unit: UNIT-ALT
Requirements covered: SWR-ALT-001 through SWR-ALT-004
Version
1.0.0
Date
2026-04-06
Author
vinu-engineer
Copyright
Medical Device Software — IEC 62304 Class B compliant. All rights reserved.
Definition in file alerts.h.
Macro Definition Documentation
ALERT_MSG_LEN
#define ALERT_MSG_LEN 96
Maximum length (including null terminator) of an alert message.
Definition at line 44 of file alerts.h.
MAX_ALERTS
#define MAX_ALERTS 5
Maximum number of alerts that can be generated from one VitalSigns.
Definition at line 41 of file alerts.h.
Referenced by patient_print_summary(), print_reading(), and update_dashboard().
Function Documentation
generate_alerts()
int generate_alerts (const VitalSigns * vitals, Alert * out, int max_out)
Generate alert records for every vital sign parameter outside its normal clinical range.
Iterates over all four vital sign parameters in this fixed order:
Heart rate
Blood pressure (systolic / diastolic)
Temperature
SpO2
For each parameter that is not ALERT_NORMAL, one Alert entry is written to out. Writing stops when either all parameters have been checked or max_out entries have been filled — whichever comes first.
Memory safety: the function never writes beyond out[max_out - 1]. Passing max_out = 0 is valid and writes nothing.
Parameters
[in] vitals Pointer to a fully populated VitalSigns structure. Must not be NULL.
[out] out Caller-allocated array to receive Alert records. Must hold at least max_out elements.
[in] max_out Maximum number of Alert entries to write.
Returns
Number of Alert records written to out (0 if all parameters are normal, or if max_out == 0).
Precondition
vitals != NULL
out != NULL || max_out == 0
Postcondition
Return value <= max_out
Requirements
SWR-ALT-001, SWR-ALT-002, SWR-ALT-003, SWR-ALT-004
Generate alert records for every vital sign parameter outside its normal clinical range.
Internal flow for each parameter:
Call the corresponding check_*() function.
If the result is not ALERT_NORMAL, write an Alert record via PUSH_ALERT.
PUSH_ALERT enforces the max_out cap before writing.
The PUSH_ALERT macro copies the parameter name with strncpy (max 31 chars
null) and formats the message with snprintf (max ALERT_MSG_LEN - 1 chars
null), guaranteeing null-termination in both fields.
Definition at line 44 of file alerts.c.
References ALERT_NORMAL, check_blood_pressure(), check_heart_rate(), check_spo2(), check_temperature(), VitalSigns::diastolic_bp, VitalSigns::heart_rate, PUSH_ALERT, VitalSigns::spo2, VitalSigns::systolic_bp, and VitalSigns::temperature.
Referenced by patient_print_summary(), print_reading(), and update_dashboard().