Patient Vital Signs Monitor: src/gui_main.c File Reference
gui_main.c File Reference
Win32 GUI entry point — Patient Vital Signs Monitor.
#include <windows.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "vitals.h"
#include "alerts.h"
#include "patient.h"
#include "gui_auth.h"
#include "hw_vitals.h"
Classes
struct AppState
Macros
#define _CRT_SECURE_NO_WARNINGS
#define APP_TITLE "Patient Vital Signs Monitor"
#define CLASS_DASHBOARD "PVM_Dashboard"
#define CLASS_LOGIN "PVM_Login"
#define CLR_CR_BG RGB(254, 226, 226)
#define CLR_CR_FG RGB(185, 28, 28)
#define CLR_DARK_TEXT RGB(30, 41, 59)
#define CLR_LIGHT_GRAY RGB(226, 232, 240)
#define CLR_NAVY RGB(30, 58, 138)
#define CLR_NEAR_WHITE RGB(248, 250, 252)
#define CLR_OK_BG RGB(220, 252, 231)
#define CLR_OK_FG RGB(21, 128, 61)
#define CLR_SLATE RGB(51, 65, 85)
#define CLR_WHITE RGB(255, 255, 255)
#define CLR_WN_BG RGB(254, 249, 195)
#define CLR_WN_FG RGB(161, 98, 7)
#define CTRL_Y (STAT_Y + STAT_H + 8) /* 342 */
#define CY CTRL_Y /* shorthand: controls top Y */
#define HDR_H 56 /* header bar */
#define IDC_BTN_ADD 1110
#define IDC_BTN_ADMIT 1010
#define IDC_BTN_CLEAR 1111
#define IDC_BTN_LOGOUT 1202
#define IDC_BTN_PAUSE 1203
#define IDC_BTN_SCEN1 1200
#define IDC_BTN_SCEN2 1201
#define IDC_LGN_BTN 102
#define IDC_LGN_ERR 103
#define IDC_LGN_PASS 101
#define IDC_LGN_USER 100
#define IDC_LIST_ALERTS 1300
#define IDC_LIST_HISTORY 1301
#define IDC_PAT_AGE 1003
#define IDC_PAT_HEIGHT 1005
#define IDC_PAT_ID 1001
#define IDC_PAT_NAME 1002
#define IDC_PAT_WEIGHT 1004
#define IDC_VIT_DIA 1103
#define IDC_VIT_HR 1101
#define IDC_VIT_SPO2 1105
#define IDC_VIT_SYS 1102
#define IDC_VIT_TEMP 1104
#define PBAR_H 38 /* patient summary bar */
#define STAT_H 44
#define STAT_Y (TILE_Y + TILE_H + 6) /* 290 */
#define TILE_H 190 /* 2×2 tile grid total */
#define TILE_Y (HDR_H + PBAR_H) /* 94 */
#define TIMER_SIM 1
#define WIN32_LEAN_AND_MEAN
#define WIN_CH 850 /* client height */
#define WIN_CW 920 /* client width */
Functions
static void attempt_login (HWND w)
Attempt login from the username/password controls.
static void create_dash_controls (HWND w)
Create all dashboard child controls. @req SWR-GUI-004.
static void create_dashboard (void)
static LRESULT CALLBACK dash_proc (HWND, UINT, WPARAM, LPARAM)
static void do_add_reading (HWND w)
Record a new vital signs reading from the vitals entry fields. @req SWR-GUI-004.
static int do_admit (HWND w)
Admit a patient from the identity fields. @req SWR-GUI-004.
static void do_clear (HWND w)
static void do_scenario (HWND w, int s)
static void draw_text_ex (HDC hdc, const char *txt, int x, int y, int w, int h, HFONT font, COLORREF fg, UINT fmt)
static void fill_rect (HDC hdc, int x, int y, int w, int h, COLORREF c)
static void font_all_children (HWND p, HFONT f)
static int get_txt (HWND p, int id, char *out, int len)
static LRESULT CALLBACK login_proc (HWND, UINT, WPARAM, LPARAM)
static HWND make_btn (HWND p, int id, const char *t, int x, int y, int w, int h)
static HWND make_edit (HWND p, int id, const char *t, int x, int y, int w, int h)
static HFONT make_font (int pt, BOOL bold)
static HWND make_label (HWND p, const char *t, int x, int y, int w, int h)
static void paint_header (HDC hdc, int cw)
Paint the application header bar. @req SWR-GUI-002.
static void paint_patient_bar (HDC hdc, int cw)
Paint the patient summary bar. @req SWR-GUI-003.
static void paint_status_banner (HDC hdc, int cw)
Paint the aggregate status banner. @req SWR-GUI-003.
static void paint_tile (HDC hdc, int tx, int ty, int tw, int th, const char *label, const char *value, const char *unit, AlertLevel level)
Paint one colour-coded vital sign tile.
static void paint_tiles (HDC hdc, int cw)
Paint the 2×2 vital sign tile grid. @req SWR-GUI-003.
static int parse_flt_field (HWND p, int id, const char *label, float *out)
static int parse_int_field (HWND p, int id, const char *label, int *out)
static void set_txt (HWND p, int id, const char *s)
static void update_dashboard (HWND w)
Refresh all dynamic dashboard content after any data change. @req SWR-GUI-003 @req SWR-GUI-004.
int WINAPI WinMain (HINSTANCE inst, HINSTANCE prev, LPSTR cmd, int show)
Variables
static AppState g_app
Detailed Description
Win32 GUI entry point — Patient Vital Signs Monitor.
Presents a two-screen application:
Login screen — authenticates the clinician (SWR-GUI-001/002).
Dashboard — live monitoring display with colour-coded vital tiles, patient data entry and session history (SWR-GUI-003/004).
All memory is static (stack/global) — no heap allocation (SYS-012).
@req SWR-GUI-001 @req SWR-GUI-002 @req SWR-GUI-003 @req SWR-GUI-004
Definition in file gui_main.c.
Macro Definition Documentation
_CRT_SECURE_NO_WARNINGS
#define _CRT_SECURE_NO_WARNINGS
Definition at line 19 of file gui_main.c.
APP_TITLE
#define APP_TITLE "Patient Vital Signs Monitor"
Definition at line 39 of file gui_main.c.
Referenced by create_dashboard(), dash_proc(), do_add_reading(), do_admit(), login_proc(), paint_header(), parse_flt_field(), parse_int_field(), and WinMain().
CLASS_DASHBOARD
#define CLASS_DASHBOARD "PVM_Dashboard"
Definition at line 38 of file gui_main.c.
Referenced by create_dashboard(), and WinMain().
CLASS_LOGIN
#define CLASS_LOGIN "PVM_Login"
Definition at line 37 of file gui_main.c.
Referenced by dash_proc(), and WinMain().
CLR_CR_BG
#define CLR_CR_BG RGB(254, 226, 226)
Definition at line 111 of file gui_main.c.
Referenced by paint_tile().
CLR_CR_FG
#define CLR_CR_FG RGB(185, 28, 28)
Definition at line 112 of file gui_main.c.
Referenced by login_proc(), paint_status_banner(), and paint_tile().
CLR_DARK_TEXT
#define CLR_DARK_TEXT RGB(30, 41, 59)
Definition at line 103 of file gui_main.c.
Referenced by login_proc(), and paint_tile().
CLR_LIGHT_GRAY
#define CLR_LIGHT_GRAY RGB(226, 232, 240)
Definition at line 102 of file gui_main.c.
Referenced by paint_patient_bar().
CLR_NAVY
#define CLR_NAVY RGB(30, 58, 138)
Definition at line 99 of file gui_main.c.
Referenced by login_proc(), and paint_header().
CLR_NEAR_WHITE
#define CLR_NEAR_WHITE RGB(248, 250, 252)
Definition at line 101 of file gui_main.c.
Referenced by dash_proc(), login_proc(), and paint_tiles().
CLR_OK_BG
#define CLR_OK_BG RGB(220, 252, 231)
Definition at line 107 of file gui_main.c.
Referenced by paint_tile().
CLR_OK_FG
#define CLR_OK_FG RGB(21, 128, 61)
Definition at line 108 of file gui_main.c.
Referenced by paint_status_banner(), and paint_tile().
CLR_SLATE
#define CLR_SLATE RGB(51, 65, 85)
Definition at line 100 of file gui_main.c.
Referenced by paint_patient_bar().
CLR_WHITE
#define CLR_WHITE RGB(255, 255, 255)
Definition at line 104 of file gui_main.c.
Referenced by login_proc(), paint_header(), and paint_status_banner().
CLR_WN_BG
#define CLR_WN_BG RGB(254, 249, 195)
Definition at line 109 of file gui_main.c.
Referenced by paint_tile().
CLR_WN_FG
#define CLR_WN_FG RGB(161, 98, 7)
Definition at line 110 of file gui_main.c.
Referenced by paint_status_banner(), and paint_tile().
CTRL_Y
#define CTRL_Y (STAT_Y + STAT_H + 8) /* 342 */
Definition at line 94 of file gui_main.c.
CY
#define CY CTRL_Y /* shorthand: controls top Y */
Definition at line 443 of file gui_main.c.
Referenced by create_dash_controls().
HDR_H
#define HDR_H 56 /* header bar */
Definition at line 88 of file gui_main.c.
Referenced by paint_header(), and paint_patient_bar().
IDC_BTN_ADD
#define IDC_BTN_ADD 1110
Definition at line 65 of file gui_main.c.
Referenced by create_dash_controls(), and dash_proc().
IDC_BTN_ADMIT
#define IDC_BTN_ADMIT 1010
Definition at line 57 of file gui_main.c.
Referenced by create_dash_controls(), and dash_proc().
IDC_BTN_CLEAR
#define IDC_BTN_CLEAR 1111
Definition at line 66 of file gui_main.c.
Referenced by create_dash_controls(), and dash_proc().
IDC_BTN_LOGOUT
#define IDC_BTN_LOGOUT 1202
Definition at line 71 of file gui_main.c.
Referenced by dash_proc().
IDC_BTN_PAUSE
#define IDC_BTN_PAUSE 1203
Definition at line 72 of file gui_main.c.
Referenced by dash_proc().
IDC_BTN_SCEN1
#define IDC_BTN_SCEN1 1200
Definition at line 69 of file gui_main.c.
Referenced by create_dash_controls(), and dash_proc().
IDC_BTN_SCEN2
#define IDC_BTN_SCEN2 1201
Definition at line 70 of file gui_main.c.
Referenced by create_dash_controls(), and dash_proc().
IDC_LGN_BTN
#define IDC_LGN_BTN 102
Definition at line 48 of file gui_main.c.
Referenced by login_proc().
IDC_LGN_ERR
#define IDC_LGN_ERR 103
Definition at line 49 of file gui_main.c.
Referenced by attempt_login(), and login_proc().
IDC_LGN_PASS
#define IDC_LGN_PASS 101
Definition at line 47 of file gui_main.c.
Referenced by attempt_login(), and login_proc().
IDC_LGN_USER
#define IDC_LGN_USER 100
Definition at line 46 of file gui_main.c.
Referenced by attempt_login(), and login_proc().
IDC_LIST_ALERTS
#define IDC_LIST_ALERTS 1300
Definition at line 78 of file gui_main.c.
Referenced by create_dash_controls(), and update_dashboard().
IDC_LIST_HISTORY
#define IDC_LIST_HISTORY 1301
Definition at line 79 of file gui_main.c.
Referenced by create_dash_controls(), and update_dashboard().
IDC_PAT_AGE
#define IDC_PAT_AGE 1003
Definition at line 54 of file gui_main.c.
Referenced by create_dash_controls(), dash_proc(), do_admit(), do_clear(), and do_scenario().
IDC_PAT_HEIGHT
#define IDC_PAT_HEIGHT 1005
Definition at line 56 of file gui_main.c.
Referenced by create_dash_controls(), dash_proc(), do_admit(), do_clear(), and do_scenario().
IDC_PAT_ID
#define IDC_PAT_ID 1001
Definition at line 52 of file gui_main.c.
Referenced by create_dash_controls(), dash_proc(), do_admit(), do_clear(), and do_scenario().
IDC_PAT_NAME
#define IDC_PAT_NAME 1002
Definition at line 53 of file gui_main.c.
Referenced by create_dash_controls(), dash_proc(), do_admit(), do_clear(), and do_scenario().
IDC_PAT_WEIGHT
#define IDC_PAT_WEIGHT 1004
Definition at line 55 of file gui_main.c.
Referenced by create_dash_controls(), dash_proc(), do_admit(), do_clear(), and do_scenario().
IDC_VIT_DIA
#define IDC_VIT_DIA 1103
Definition at line 62 of file gui_main.c.
Referenced by create_dash_controls(), do_add_reading(), and do_clear().
IDC_VIT_HR
#define IDC_VIT_HR 1101
Definition at line 60 of file gui_main.c.
Referenced by create_dash_controls(), do_add_reading(), and do_clear().
IDC_VIT_SPO2
#define IDC_VIT_SPO2 1105
Definition at line 64 of file gui_main.c.
Referenced by create_dash_controls(), do_add_reading(), and do_clear().
IDC_VIT_SYS
#define IDC_VIT_SYS 1102
Definition at line 61 of file gui_main.c.
Referenced by create_dash_controls(), do_add_reading(), and do_clear().
IDC_VIT_TEMP
#define IDC_VIT_TEMP 1104
Definition at line 63 of file gui_main.c.
Referenced by create_dash_controls(), do_add_reading(), and do_clear().
PBAR_H
#define PBAR_H 38 /* patient summary bar */
Definition at line 89 of file gui_main.c.
Referenced by paint_patient_bar().
STAT_H
#define STAT_H 44
Definition at line 93 of file gui_main.c.
Referenced by paint_status_banner().
STAT_Y
#define STAT_Y (TILE_Y + TILE_H + 6) /* 290 */
Definition at line 92 of file gui_main.c.
Referenced by paint_status_banner().
TILE_H
#define TILE_H 190 /* 2×2 tile grid total */
Definition at line 91 of file gui_main.c.
Referenced by paint_tiles().
TILE_Y
#define TILE_Y (HDR_H + PBAR_H) /* 94 */
Definition at line 90 of file gui_main.c.
Referenced by paint_tiles().
TIMER_SIM
#define TIMER_SIM 1
Definition at line 75 of file gui_main.c.
Referenced by dash_proc().
WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
Definition at line 22 of file gui_main.c.
WIN_CH
#define WIN_CH 850 /* client height */
Definition at line 85 of file gui_main.c.
Referenced by create_dashboard().
WIN_CW
#define WIN_CW 920 /* client width */
Definition at line 84 of file gui_main.c.
Referenced by create_dashboard(), and dash_proc().
Function Documentation
attempt_login()
void attempt_login (HWND w) static
Attempt login from the username/password controls.
On success: destroys the login window and opens the dashboard. On failure: shows an error message inside the window.
@req SWR-GUI-001 @req SWR-GUI-002
Definition at line 862 of file gui_main.c.
References auth_display_name(), AUTH_MAX_CREDENTIAL_LEN, auth_validate(), create_dashboard(), g_app, get_txt(), IDC_LGN_ERR, IDC_LGN_PASS, and IDC_LGN_USER.
Referenced by login_proc().
create_dash_controls()
void create_dash_controls (HWND w) static
Create all dashboard child controls. @req SWR-GUI-004.
Definition at line 449 of file gui_main.c.
References CY, g_app, IDC_BTN_ADD, IDC_BTN_ADMIT, IDC_BTN_CLEAR, IDC_BTN_SCEN1, IDC_BTN_SCEN2, IDC_LIST_ALERTS, IDC_LIST_HISTORY, IDC_PAT_AGE, IDC_PAT_HEIGHT, IDC_PAT_ID, IDC_PAT_NAME, IDC_PAT_WEIGHT, IDC_VIT_DIA, IDC_VIT_HR, IDC_VIT_SPO2, IDC_VIT_SYS, IDC_VIT_TEMP, make_btn(), make_edit(), and make_label().
Referenced by dash_proc().
create_dashboard()
void create_dashboard (void) static
Definition at line 1004 of file gui_main.c.
References APP_TITLE, CLASS_DASHBOARD, g_app, WIN_CH, and WIN_CW.
Referenced by attempt_login().
dash_proc()
LRESULT CALLBACK dash_proc (HWND w, UINT msg, WPARAM wp, LPARAM lp) static
Definition at line 726 of file gui_main.c.
References APP_TITLE, CLASS_LOGIN, CLR_NEAR_WHITE, create_dash_controls(), do_add_reading(), do_admit(), do_clear(), do_scenario(), font_all_children(), g_app, hw_get_next_reading(), hw_init(), IDC_BTN_ADD, IDC_BTN_ADMIT, IDC_BTN_CLEAR, IDC_BTN_LOGOUT, IDC_BTN_PAUSE, IDC_BTN_SCEN1, IDC_BTN_SCEN2, IDC_PAT_AGE, IDC_PAT_HEIGHT, IDC_PAT_ID, IDC_PAT_NAME, IDC_PAT_WEIGHT, make_btn(), paint_header(), paint_patient_bar(), paint_status_banner(), paint_tiles(), patient_add_reading(), patient_init(), patient_is_full(), set_txt(), TIMER_SIM, update_dashboard(), and WIN_CW.
Referenced by WinMain().
do_add_reading()
void do_add_reading (HWND w) static
Record a new vital signs reading from the vitals entry fields. @req SWR-GUI-004.
Definition at line 642 of file gui_main.c.
References APP_TITLE, VitalSigns::diastolic_bp, do_admit(), g_app, VitalSigns::heart_rate, IDC_VIT_DIA, IDC_VIT_HR, IDC_VIT_SPO2, IDC_VIT_SYS, IDC_VIT_TEMP, parse_flt_field(), parse_int_field(), patient_add_reading(), VitalSigns::spo2, VitalSigns::systolic_bp, VitalSigns::temperature, and update_dashboard().
Referenced by dash_proc().
do_admit()
int do_admit (HWND w) static
Admit a patient from the identity fields. @req SWR-GUI-004.
Definition at line 620 of file gui_main.c.
References APP_TITLE, g_app, get_txt(), IDC_PAT_AGE, IDC_PAT_HEIGHT, IDC_PAT_ID, IDC_PAT_NAME, IDC_PAT_WEIGHT, MAX_NAME_LEN, parse_flt_field(), parse_int_field(), patient_init(), and update_dashboard().
Referenced by dash_proc(), do_add_reading(), and do_scenario().
do_clear()
void do_clear (HWND w) static
Clear all session data and reset the input fields to default values.
Definition at line 663 of file gui_main.c.
References g_app, IDC_PAT_AGE, IDC_PAT_HEIGHT, IDC_PAT_ID, IDC_PAT_NAME, IDC_PAT_WEIGHT, IDC_VIT_DIA, IDC_VIT_HR, IDC_VIT_SPO2, IDC_VIT_SYS, IDC_VIT_TEMP, set_txt(), and update_dashboard().
Referenced by dash_proc().
do_scenario()
void do_scenario (HWND w, int s) static
Load a pre-built demonstration scenario.
Definition at line 681 of file gui_main.c.
References do_admit(), g_app, IDC_PAT_AGE, IDC_PAT_HEIGHT, IDC_PAT_ID, IDC_PAT_NAME, IDC_PAT_WEIGHT, patient_add_reading(), set_txt(), and update_dashboard().
Referenced by dash_proc().
draw_text_ex()
void draw_text_ex (HDC hdc, const char * txt, int x, int y, int w, int h, HFONT font, COLORREF fg, UINT fmt) static
Definition at line 172 of file gui_main.c.
Referenced by login_proc(), paint_header(), paint_patient_bar(), paint_status_banner(), and paint_tile().
fill_rect()
void fill_rect (HDC hdc, int x, int y, int w, int h, COLORREF c) static
Definition at line 164 of file gui_main.c.
Referenced by login_proc(), paint_header(), paint_patient_bar(), paint_status_banner(), paint_tile(), and paint_tiles().
font_all_children()
void font_all_children (HWND p, HFONT f) static
Definition at line 431 of file gui_main.c.
Referenced by dash_proc(), and login_proc().
get_txt()
int get_txt (HWND p, int id, char * out, int len) static
Definition at line 565 of file gui_main.c.
Referenced by attempt_login(), do_admit(), parse_flt_field(), and parse_int_field().
login_proc()
LRESULT CALLBACK login_proc (HWND w, UINT msg, WPARAM wp, LPARAM lp) static
Definition at line 887 of file gui_main.c.
References APP_TITLE, attempt_login(), CLR_CR_FG, CLR_DARK_TEXT, CLR_NAVY, CLR_NEAR_WHITE, CLR_WHITE, draw_text_ex(), fill_rect(), font_all_children(), g_app, IDC_LGN_BTN, IDC_LGN_ERR, IDC_LGN_PASS, IDC_LGN_USER, make_edit(), and make_label().
Referenced by WinMain().
make_btn()
HWND make_btn (HWND p, int id, const char * t, int x, int y, int w, int h) static
Definition at line 423 of file gui_main.c.
References g_app.
Referenced by create_dash_controls(), and dash_proc().
make_edit()
HWND make_edit (HWND p, int id, const char * t, int x, int y, int w, int h) static
Definition at line 415 of file gui_main.c.
References g_app.
Referenced by create_dash_controls(), and login_proc().
make_font()
HFONT make_font (int pt, BOOL bold) static
Create a Segoe UI font at the requested point size.
Definition at line 155 of file gui_main.c.
Referenced by WinMain().
make_label()
HWND make_label (HWND p, const char * t, int x, int y, int w, int h) static
Definition at line 409 of file gui_main.c.
References g_app.
Referenced by create_dash_controls(), and login_proc().
paint_header()
void paint_header (HDC hdc, int cw) static
Paint the application header bar. @req SWR-GUI-002.
Definition at line 192 of file gui_main.c.
References APP_TITLE, CLR_NAVY, CLR_WHITE, draw_text_ex(), fill_rect(), g_app, and HDR_H.
Referenced by dash_proc().
paint_patient_bar()
void paint_patient_bar (HDC hdc, int cw) static
Paint the patient summary bar. @req SWR-GUI-003.
Definition at line 232 of file gui_main.c.
References bmi_category(), calculate_bmi(), CLR_LIGHT_GRAY, CLR_SLATE, draw_text_ex(), fill_rect(), g_app, HDR_H, MAX_READINGS, and PBAR_H.
Referenced by dash_proc().
paint_status_banner()
void paint_status_banner (HDC hdc, int cw) static
Paint the aggregate status banner. @req SWR-GUI-003.
Definition at line 375 of file gui_main.c.
References ALERT_CRITICAL, ALERT_NORMAL, ALERT_WARNING, CLR_CR_FG, CLR_OK_FG, CLR_WHITE, CLR_WN_FG, draw_text_ex(), fill_rect(), g_app, patient_current_status(), STAT_H, and STAT_Y.
Referenced by dash_proc().
paint_tile()
void paint_tile (HDC hdc, int tx, int ty, int tw, int th, const char * label, const char * value, const char * unit, AlertLevel level) static
Paint one colour-coded vital sign tile.
Each tile shows the parameter label, measured value + unit, and a colour-coded badge (NORMAL / WARNING / CRITICAL).
@req SWR-GUI-003
Definition at line 266 of file gui_main.c.
References ALERT_CRITICAL, ALERT_WARNING, CLR_CR_BG, CLR_CR_FG, CLR_DARK_TEXT, CLR_OK_BG, CLR_OK_FG, CLR_WN_BG, CLR_WN_FG, draw_text_ex(), fill_rect(), and g_app.
Referenced by paint_tiles().
paint_tiles()
void paint_tiles (HDC hdc, int cw) static
Paint the 2×2 vital sign tile grid. @req SWR-GUI-003.
Definition at line 325 of file gui_main.c.
References ALERT_NORMAL, check_blood_pressure(), check_heart_rate(), check_spo2(), check_temperature(), CLR_NEAR_WHITE, VitalSigns::diastolic_bp, fill_rect(), g_app, VitalSigns::heart_rate, paint_tile(), patient_latest_reading(), VitalSigns::spo2, VitalSigns::systolic_bp, VitalSigns::temperature, TILE_H, and TILE_Y.
Referenced by dash_proc().
parse_flt_field()
int parse_flt_field (HWND p, int id, const char * label, float * out) static
Definition at line 595 of file gui_main.c.
References APP_TITLE, and get_txt().
Referenced by do_add_reading(), and do_admit().
parse_int_field()
int parse_int_field (HWND p, int id, const char * label, int * out) static
Definition at line 578 of file gui_main.c.
References APP_TITLE, and get_txt().
Referenced by do_add_reading(), and do_admit().
set_txt()
void set_txt (HWND p, int id, const char * s) static
Definition at line 573 of file gui_main.c.
Referenced by dash_proc(), do_clear(), and do_scenario().
update_dashboard()
void update_dashboard (HWND hwnd) static
Refresh all dynamic dashboard content after any data change. @req SWR-GUI-003 @req SWR-GUI-004.
Definition at line 508 of file gui_main.c.
References ALERT_CRITICAL, alert_level_str(), VitalSigns::diastolic_bp, g_app, generate_alerts(), VitalSigns::heart_rate, IDC_LIST_ALERTS, IDC_LIST_HISTORY, Alert::level, MAX_ALERTS, overall_alert_level(), patient_latest_reading(), VitalSigns::spo2, VitalSigns::systolic_bp, and VitalSigns::temperature.
Referenced by dash_proc(), do_add_reading(), do_admit(), do_clear(), and do_scenario().
WinMain()
int WINAPI WinMain (HINSTANCE inst, HINSTANCE prev, LPSTR cmd, int show)
Definition at line 1024 of file gui_main.c.
References APP_TITLE, CLASS_DASHBOARD, CLASS_LOGIN, dash_proc(), g_app, login_proc(), and make_font().
Variable Documentation
g_app
AppState g_app static
Definition at line 140 of file gui_main.c.
Referenced by attempt_login(), create_dash_controls(), create_dashboard(), dash_proc(), do_add_reading(), do_admit(), do_clear(), do_scenario(), login_proc(), make_btn(), make_edit(), make_label(), paint_header(), paint_patient_bar(), paint_status_banner(), paint_tile(), paint_tiles(), update_dashboard(), and WinMain().