Patient Vital Signs Monitor: src/main.c File Reference
main.c File Reference
Application entry point — simulated patient monitoring session.
#include <stdio.h>
#include "patient.h"
Functions
int main (void)
Application entry point.
static void monitor_patient (void)
Run the monitoring session for Patient 1 (deterioration scenario).
static void monitor_second_patient (void)
Run the monitoring session for Patient 2 (bradycardia scenario).
static void print_reading (int num, const VitalSigns *v)
Print a single vital sign reading with per-parameter status and alerts.
Detailed Description
Application entry point — simulated patient monitoring session.
Demonstrates the Patient Vital Signs Monitor with two simulated patients:
Patient 1 — Sarah Johnson (ID 1001) Simulates a deterioration trajectory across three readings:
Reading 1: All normal (admission baseline)
Reading 2: All WARNING (developing sepsis-like presentation)
Reading 3: Temperature and SpO2 CRITICAL (acute crisis)
Patient 2 — David Okonkwo (ID 1002) Simulates an isolated bradycardia episode:
Reading 1: All normal (stable)
Reading 2: Heart rate CRITICAL (severe bradycardia at 38 bpm)
Output Format
Each reading shows per-parameter classification in brackets and any active alerts prefixed with ! WARNING or !! CRITICAL. A summary block is printed at the end of each patient's session.
Version
1.0.0
Date
2026-04-06
Author
vinu-engineer
Definition in file main.c.
Function Documentation
main()
int main (void)
Application entry point.
Returns
0 on successful completion.
Definition at line 147 of file main.c.
References monitor_patient(), and monitor_second_patient().
monitor_patient()
void monitor_patient (void) static
Run the monitoring session for Patient 1 (deterioration scenario).
Admits Sarah Johnson and records three readings that progress from NORMAL → WARNING → CRITICAL to demonstrate full alert escalation.
Definition at line 73 of file main.c.
References PatientInfo::age, bmi_category(), calculate_bmi(), PatientInfo::height_m, PatientInfo::id, PatientRecord::info, PatientInfo::name, patient_add_reading(), patient_init(), patient_print_summary(), print_reading(), and PatientInfo::weight_kg.
Referenced by main().
monitor_second_patient()
void monitor_second_patient (void) static
Run the monitoring session for Patient 2 (bradycardia scenario).
Admits David Okonkwo and records two readings, with the second showing isolated severe bradycardia (38 bpm) while all other parameters remain normal.
Definition at line 114 of file main.c.
References PatientInfo::age, bmi_category(), calculate_bmi(), PatientInfo::height_m, PatientInfo::id, PatientRecord::info, PatientInfo::name, patient_add_reading(), patient_init(), patient_print_summary(), print_reading(), and PatientInfo::weight_kg.
Referenced by main().
print_reading()
void print_reading (int num, const VitalSigns * v) static
Print a single vital sign reading with per-parameter status and alerts.
Parameters
[in] num Reading sequence number (1-based), used in the heading.
[in] v Pointer to the VitalSigns to display. Must not be NULL.
Definition at line 38 of file main.c.
References ALERT_CRITICAL, alert_level_str(), check_blood_pressure(), check_heart_rate(), check_spo2(), check_temperature(), VitalSigns::diastolic_bp, generate_alerts(), VitalSigns::heart_rate, Alert::level, MAX_ALERTS, overall_alert_level(), VitalSigns::spo2, VitalSigns::systolic_bp, and VitalSigns::temperature.
Referenced by monitor_patient(), and monitor_second_patient().