Patient Vital Signs Monitor: include/patient.h File Reference
patient.h File Reference
Patient record management — demographic data and vital sign history.
#include "vitals.h"
#include "alerts.h"
Classes
struct PatientInfo
Demographic information for a monitored patient.
struct PatientRecord
Complete patient record including demographics and vital sign history.
Macros
#define MAX_NAME_LEN 64
Maximum length of a patient name string (including null terminator).
#define MAX_READINGS 10
Maximum number of vital sign readings stored per patient.
Functions
int patient_add_reading (PatientRecord *rec, const VitalSigns *v)
Append a vital sign reading to the patient's history.
AlertLevel patient_current_status (const PatientRecord *rec)
Return the overall alert status derived from the latest reading.
void patient_init (PatientRecord *rec, int id, const char *name, int age, float weight_kg, float height_m)
Initialise a PatientRecord with demographic data.
int patient_is_full (const PatientRecord *rec)
Check whether the patient record's reading buffer is full.
const VitalSigns * patient_latest_reading (const PatientRecord *rec)
Return a pointer to the most recently added vital sign reading.
void patient_print_summary (const PatientRecord *rec)
Print a formatted patient summary to stdout.
Detailed Description
Patient record management — demographic data and vital sign history.
This module provides the top-level data structure for a monitored patient and the functions to manage their vital sign history. It composes the vitals and alerts modules to provide a complete patient-status API.
Architecture Position
PatientRecord sits at the top of the module hierarchy:
patient.h
  └── vitals.h   (classification of individual readings)
  └── alerts.h   (alert record generation)
Storage Model
Readings are stored in a fixed-size array (MAX_READINGS = 10). Once full, further additions are rejected (patient_add_reading() returns 0). This design avoids dynamic memory allocation, a requirement for safety-critical embedded software under IEC 62304.
IEC 62304 Traceability
Software Unit: UNIT-PAT
Requirements covered: SWR-PAT-001 through SWR-PAT-006
Version
1.0.0
Date
2026-04-06
Author
vinu-engineer
Copyright
Medical Device Software — IEC 62304 Class B compliant. All rights reserved.
Definition in file patient.h.
Macro Definition Documentation
MAX_NAME_LEN
#define MAX_NAME_LEN 64
Maximum length of a patient name string (including null terminator).
Definition at line 50 of file patient.h.
Referenced by do_admit(), and patient_init().
MAX_READINGS
#define MAX_READINGS 10
Maximum number of vital sign readings stored per patient.
Definition at line 47 of file patient.h.
Referenced by paint_patient_bar(), patient_add_reading(), patient_is_full(), and patient_print_summary().
Function Documentation
patient_add_reading()
int patient_add_reading (PatientRecord * rec, const VitalSigns * v)
Append a vital sign reading to the patient's history.
The VitalSigns structure is copied by value into the internal array. If the record is already full (reading_count == MAX_READINGS), the record is left unchanged and 0 is returned.
Parameters
[in,out] rec Pointer to an initialised PatientRecord. Must not be NULL.
[in] v Pointer to the VitalSigns reading to append. Copied by value; the caller may free or reuse v afterwards.
Returns
1 if the reading was successfully appended, 0 if the buffer is full.
Precondition
rec != NULL
v != NULL
Postcondition
On success: rec->reading_count is incremented by 1.
On failure: rec is unchanged.
Requirement
SWR-PAT-002
Append a vital sign reading to the patient's history.
VitalSigns is copied by value (struct assignment), so the caller retains ownership of the original and may reuse the variable.
Definition at line 56 of file patient.c.
References MAX_READINGS, PatientRecord::reading_count, and PatientRecord::readings.
Referenced by dash_proc(), do_add_reading(), do_scenario(), monitor_patient(), and monitor_second_patient().
patient_current_status()
AlertLevel patient_current_status (const PatientRecord * rec)
Return the overall alert status derived from the latest reading.
Delegates to overall_alert_level() on the most recent reading. Returns ALERT_NORMAL if no readings have been recorded yet.
Parameters
[in] rec Pointer to an initialised PatientRecord. Must not be NULL.
Returns
AlertLevel based on the latest VitalSigns, or ALERT_NORMAL if reading_count == 0.
Requirement
SWR-PAT-004
Return the overall alert status derived from the latest reading.
Delegates entirely to overall_alert_level() to keep classification logic centralised in vitals.c — consistent with single-responsibility.
Definition at line 78 of file patient.c.
References ALERT_NORMAL, overall_alert_level(), and patient_latest_reading().
Referenced by paint_status_banner(), and patient_print_summary().
patient_init()
void patient_init (PatientRecord * rec, int id, const char * name, int age, float weight_kg, float height_m)
Initialise a PatientRecord with demographic data.
Zero-fills the entire structure before populating fields. reading_count is set to 0. The name string is copied with truncation to MAX_NAME_LEN - 1 characters and guaranteed null-termination.
Parameters
[out] rec Pointer to the record to initialise. Must not be NULL.
[in] id Unique patient identifier.
[in] name Null-terminated patient name string. Must not be NULL.
[in] age Patient age in years.
[in] weight_kg Body weight in kilograms.
[in] height_m Height in metres.
Precondition
rec != NULL
name != NULL
Postcondition
rec->reading_count == 0
Requirement
SWR-PAT-001
Initialise a PatientRecord with demographic data.
memset(0) ensures that any unused readings array slots contain all-zero VitalSigns, which classify as CRITICAL across all parameters — a deliberately safe default that prevents silent display of uninitialised data.
Definition at line 38 of file patient.c.
References PatientInfo::age, PatientInfo::height_m, PatientInfo::id, PatientRecord::info, MAX_NAME_LEN, PatientInfo::name, PatientRecord::reading_count, and PatientInfo::weight_kg.
Referenced by dash_proc(), do_admit(), monitor_patient(), and monitor_second_patient().
patient_is_full()
int patient_is_full (const PatientRecord * rec)
Check whether the patient record's reading buffer is full.
Parameters
[in] rec Pointer to an initialised PatientRecord. Must not be NULL.
Returns
Non-zero (true) if reading_count == MAX_READINGS, zero otherwise.
Requirement
SWR-PAT-005
Check whether the patient record's reading buffer is full.
Definition at line 88 of file patient.c.
References MAX_READINGS, and PatientRecord::reading_count.
Referenced by dash_proc().
patient_latest_reading()
const VitalSigns * patient_latest_reading (const PatientRecord * rec)
Return a pointer to the most recently added vital sign reading.
Parameters
[in] rec Pointer to an initialised PatientRecord. Must not be NULL.
Returns
Pointer to the latest VitalSigns entry within rec, or NULL if no readings have been recorded (reading_count == 0).
Warning
The returned pointer points into the PatientRecord's internal array. It becomes invalid if rec is destroyed or moved.
Requirement
SWR-PAT-003
Return a pointer to the most recently added vital sign reading.
Index arithmetic: the last valid slot is readings[reading_count - 1].
Definition at line 67 of file patient.c.
References PatientRecord::reading_count, and PatientRecord::readings.
Referenced by paint_tiles(), patient_current_status(), patient_print_summary(), and update_dashboard().
patient_print_summary()
void patient_print_summary (const PatientRecord * rec)
Print a formatted patient summary to stdout.
Outputs demographic data, BMI, the latest vital signs with individual classifications, the overall status, and any active alerts. Output is suitable for a 80-column terminal.
Parameters
[in] rec Pointer to an initialised PatientRecord. Must not be NULL.
Note
This function writes to stdout. In unit tests, redirect stdout before calling to keep test output clean.
Requirement
SWR-PAT-006
Print a formatted patient summary to stdout.
Generates alerts inline for the latest reading using generate_alerts(). Output is formatted for an 80-column terminal with box-drawing borders.
Definition at line 98 of file patient.c.
References PatientInfo::age, ALERT_CRITICAL, alert_level_str(), bmi_category(), calculate_bmi(), check_blood_pressure(), check_heart_rate(), check_spo2(), check_temperature(), VitalSigns::diastolic_bp, generate_alerts(), VitalSigns::heart_rate, PatientInfo::height_m, PatientInfo::id, PatientRecord::info, Alert::level, MAX_ALERTS, MAX_READINGS, PatientInfo::name, patient_current_status(), patient_latest_reading(), PatientRecord::reading_count, VitalSigns::spo2, VitalSigns::systolic_bp, VitalSigns::temperature, and PatientInfo::weight_kg.
Referenced by monitor_patient(), and monitor_second_patient().