Patient Vital Signs Monitor: src/patient.c File Reference
patient.c File Reference
Implementation of patient record management functions.
#include "patient.h"
#include <stdio.h>
#include <string.h>
Macros
#define _CRT_SECURE_NO_WARNINGS
Functions
int patient_add_reading (PatientRecord *rec, const VitalSigns *v)
Append a vital signs reading, enforcing the MAX_READINGS cap.
AlertLevel patient_current_status (const PatientRecord *rec)
Return the overall status from the latest reading.
void patient_init (PatientRecord *rec, int id, const char *name, int age, float weight_kg, float height_m)
Initialise a PatientRecord, zeroing all fields before populating.
int patient_is_full (const PatientRecord *rec)
Check if the reading buffer is at capacity.
const VitalSigns * patient_latest_reading (const PatientRecord *rec)
Return a pointer to the most recent reading, or NULL if none exist.
void patient_print_summary (const PatientRecord *rec)
Print a formatted patient summary including vitals and active alerts.
Detailed Description
Implementation of patient record management functions.
Implements all functions declared in patient.h. The module uses only static memory (no heap allocation) in compliance with IEC 62304 Class B guidance for embedded medical device software.
Memory Safety
patient_init() zero-fills the entire record before writing fields, preventing stale data from a previous session.
strncpy is used with an explicit length limit and explicit null-termination to guard against buffer overrun.
patient_add_reading() enforces the MAX_READINGS cap and returns a status code so callers can detect and handle overflow.
Version
1.0.0
Date
2026-04-06
Author
vinu-engineer
Definition in file patient.c.
Macro Definition Documentation
_CRT_SECURE_NO_WARNINGS
#define _CRT_SECURE_NO_WARNINGS
Definition at line 24 of file patient.c.
Function Documentation
patient_add_reading()
int patient_add_reading (PatientRecord * rec, const VitalSigns * v)
Append a vital signs reading, enforcing the MAX_READINGS cap.
Append a vital sign reading to the patient's history.
VitalSigns is copied by value (struct assignment), so the caller retains ownership of the original and may reuse the variable.
Definition at line 56 of file patient.c.
References MAX_READINGS, PatientRecord::reading_count, and PatientRecord::readings.
Referenced by dash_proc(), do_add_reading(), do_scenario(), monitor_patient(), and monitor_second_patient().
patient_current_status()
AlertLevel patient_current_status (const PatientRecord * rec)
Return the overall status from the latest reading.
Return the overall alert status derived from the latest reading.
Delegates entirely to overall_alert_level() to keep classification logic centralised in vitals.c — consistent with single-responsibility.
Definition at line 78 of file patient.c.
References ALERT_NORMAL, overall_alert_level(), and patient_latest_reading().
Referenced by paint_status_banner(), and patient_print_summary().
patient_init()
void patient_init (PatientRecord * rec, int id, const char * name, int age, float weight_kg, float height_m)
Initialise a PatientRecord, zeroing all fields before populating.
Initialise a PatientRecord with demographic data.
memset(0) ensures that any unused readings array slots contain all-zero VitalSigns, which classify as CRITICAL across all parameters — a deliberately safe default that prevents silent display of uninitialised data.
Definition at line 38 of file patient.c.
References PatientInfo::age, PatientInfo::height_m, PatientInfo::id, PatientRecord::info, MAX_NAME_LEN, PatientInfo::name, PatientRecord::reading_count, and PatientInfo::weight_kg.
Referenced by dash_proc(), do_admit(), monitor_patient(), and monitor_second_patient().
patient_is_full()
int patient_is_full (const PatientRecord * rec)
Check if the reading buffer is at capacity.
Check whether the patient record's reading buffer is full.
Definition at line 88 of file patient.c.
References MAX_READINGS, and PatientRecord::reading_count.
Referenced by dash_proc().
patient_latest_reading()
const VitalSigns * patient_latest_reading (const PatientRecord * rec)
Return a pointer to the most recent reading, or NULL if none exist.
Return a pointer to the most recently added vital sign reading.
Index arithmetic: the last valid slot is readings[reading_count - 1].
Definition at line 67 of file patient.c.
References PatientRecord::reading_count, and PatientRecord::readings.
Referenced by paint_tiles(), patient_current_status(), patient_print_summary(), and update_dashboard().
patient_print_summary()
void patient_print_summary (const PatientRecord * rec)
Print a formatted patient summary including vitals and active alerts.
Print a formatted patient summary to stdout.
Generates alerts inline for the latest reading using generate_alerts(). Output is formatted for an 80-column terminal with box-drawing borders.
Definition at line 98 of file patient.c.
References PatientInfo::age, ALERT_CRITICAL, alert_level_str(), bmi_category(), calculate_bmi(), check_blood_pressure(), check_heart_rate(), check_spo2(), check_temperature(), VitalSigns::diastolic_bp, generate_alerts(), VitalSigns::heart_rate, PatientInfo::height_m, PatientInfo::id, PatientRecord::info, Alert::level, MAX_ALERTS, MAX_READINGS, PatientInfo::name, patient_current_status(), patient_latest_reading(), PatientRecord::reading_count, VitalSigns::spo2, VitalSigns::systolic_bp, VitalSigns::temperature, and PatientInfo::weight_kg.
Referenced by monitor_patient(), and monitor_second_patient().