Patient Vital Signs Monitor: src/vitals.c File Reference
vitals.c File Reference
Implementation of vital sign validation and BMI calculation.
#include "vitals.h"
Functions
const char * alert_level_str (AlertLevel level)
Convert an AlertLevel enum to a display string.
const char * bmi_category (float bmi)
Map a BMI value to a WHO weight-status category string.
float calculate_bmi (float weight_kg, float height_m)
Calculate BMI using the standard WHO formula.
AlertLevel check_blood_pressure (int systolic, int diastolic)
Classify a blood pressure reading.
AlertLevel check_heart_rate (int bpm)
Classify a heart rate reading.
AlertLevel check_spo2 (int spo2)
Classify an SpO2 reading.
AlertLevel check_temperature (float temp_c)
Classify a temperature reading.
AlertLevel overall_alert_level (const VitalSigns *vitals)
Return the highest alert level across all four vital parameters.
Detailed Description
Implementation of vital sign validation and BMI calculation.
Implements all functions declared in vitals.h. Threshold values are defined as inline literals within each function rather than as macros to keep the code readable and auditable during IEC 62304 code review.
Threshold Sources
Heart rate: AHA/ACC 2019 guidelines
Blood pressure: JNC-8 / ESC 2018 guidelines
Temperature: WHO clinical reference ranges
SpO2: British Thoracic Society supplemental oxygen guidelines
BMI: WHO classification 2004
Version
1.0.0
Date
2026-04-06
Author
vinu-engineer
Definition in file vitals.c.
Function Documentation
alert_level_str()
const char * alert_level_str (AlertLevel level)
Convert an AlertLevel enum to a display string.
Convert an AlertLevel value to a human-readable string.
Returns "UNKNOWN" for any value not in the enum to defend against undefined enum casts — important for IEC 62304 defensive coding.
Definition at line 135 of file vitals.c.
References ALERT_CRITICAL, ALERT_NORMAL, and ALERT_WARNING.
Referenced by patient_print_summary(), print_reading(), and update_dashboard().
bmi_category()
const char * bmi_category (float bmi)
Map a BMI value to a WHO weight-status category string.
Return the WHO BMI category string for a given BMI value.
Uses half-open intervals consistent with WHO classification 2004.
Definition at line 121 of file vitals.c.
Referenced by monitor_patient(), monitor_second_patient(), paint_patient_bar(), and patient_print_summary().
calculate_bmi()
float calculate_bmi (float weight_kg, float height_m)
Calculate BMI using the standard WHO formula.
Calculate Body Mass Index (BMI) from weight and height.
BMI = weight_kg / (height_m^2). Returns -1.0 for invalid (zero or negative) height to allow callers to distinguish an error from a legitimate very-low BMI.
Definition at line 111 of file vitals.c.
Referenced by monitor_patient(), monitor_second_patient(), paint_patient_bar(), and patient_print_summary().
check_blood_pressure()
AlertLevel check_blood_pressure (int systolic, int diastolic)
Classify a blood pressure reading.
Classify a blood pressure reading against clinical thresholds.
Implements SWR-VIT-002 threshold logic. Critical thresholds are evaluated first (fail-safe ordering). If either systolic or diastolic is critical, CRITICAL is returned. If either is outside the normal range, WARNING is returned.
Definition at line 45 of file vitals.c.
References ALERT_CRITICAL, ALERT_NORMAL, and ALERT_WARNING.
Referenced by generate_alerts(), overall_alert_level(), paint_tiles(), patient_print_summary(), and print_reading().
check_heart_rate()
AlertLevel check_heart_rate (int bpm)
Classify a heart rate reading.
Classify a heart rate reading against clinical thresholds.
Implements SWR-VIT-001 threshold logic. Critical: bpm < 40 (severe bradycardia) or bpm > 150 (severe tachycardia). Warning: bpm < 60 or bpm > 100. Normal: 60 <= bpm <= 100.
Definition at line 31 of file vitals.c.
References ALERT_CRITICAL, ALERT_NORMAL, and ALERT_WARNING.
Referenced by generate_alerts(), overall_alert_level(), paint_tiles(), patient_print_summary(), and print_reading().
check_spo2()
AlertLevel check_spo2 (int spo2)
Classify an SpO2 reading.
Classify a peripheral oxygen saturation reading.
Implements SWR-VIT-004 threshold logic. <90% = hypoxaemia (CRITICAL). 90–94% = mild hypoxaemia (WARNING). 95–100% = normal saturation.
Definition at line 75 of file vitals.c.
References ALERT_CRITICAL, ALERT_NORMAL, and ALERT_WARNING.
Referenced by generate_alerts(), overall_alert_level(), paint_tiles(), patient_print_summary(), and print_reading().
check_temperature()
AlertLevel check_temperature (float temp_c)
Classify a temperature reading.
Classify a body temperature reading against clinical thresholds.
Implements SWR-VIT-003 threshold logic. <35.0 °C = hypothermia (CRITICAL). >39.5 °C = hyperpyrexia (CRITICAL). Values outside 36.1–37.2 but within critical bounds = WARNING.
Definition at line 61 of file vitals.c.
References ALERT_CRITICAL, ALERT_NORMAL, and ALERT_WARNING.
Referenced by generate_alerts(), overall_alert_level(), paint_tiles(), patient_print_summary(), and print_reading().
overall_alert_level()
AlertLevel overall_alert_level (const VitalSigns * vitals)
Return the highest alert level across all four vital parameters.
Return the highest alert level across all vital sign parameters.
Implements SWR-VIT-005. Iterates all four checks and tracks the maximum. Uses a fixed-size array to avoid branch explosion and keep cyclomatic complexity low for IEC 62304 review.
Definition at line 88 of file vitals.c.
References ALERT_NORMAL, check_blood_pressure(), check_heart_rate(), check_spo2(), check_temperature(), VitalSigns::diastolic_bp, VitalSigns::heart_rate, VitalSigns::spo2, VitalSigns::systolic_bp, and VitalSigns::temperature.
Referenced by patient_current_status(), print_reading(), and update_dashboard().