Patient Vital Signs Monitor: include/vitals.h File Reference
vitals.h File Reference
Vital signs data types, thresholds, and validation functions.
Classes
struct VitalSigns
A single set of patient vital sign measurements.
Enumerations
enum AlertLevel { ALERT_NORMAL = 0 , ALERT_WARNING = 1 , ALERT_CRITICAL = 2 }
Classification of a vital sign reading relative to clinical norms.
Functions
const char * alert_level_str (AlertLevel level)
Convert an AlertLevel value to a human-readable string.
const char * bmi_category (float bmi)
Return the WHO BMI category string for a given BMI value.
float calculate_bmi (float weight_kg, float height_m)
Calculate Body Mass Index (BMI) from weight and height.
AlertLevel check_blood_pressure (int systolic, int diastolic)
Classify a blood pressure reading against clinical thresholds.
AlertLevel check_heart_rate (int bpm)
Classify a heart rate reading against clinical thresholds.
AlertLevel check_spo2 (int spo2)
Classify a peripheral oxygen saturation reading.
AlertLevel check_temperature (float temp_c)
Classify a body temperature reading against clinical thresholds.
AlertLevel overall_alert_level (const VitalSigns *vitals)
Return the highest alert level across all vital sign parameters.
Detailed Description
Vital signs data types, thresholds, and validation functions.
This module defines the core data structures and validation logic for patient vital signs. Each parameter is evaluated against clinically defined thresholds derived from AHA/ACC guidelines and classified into one of three alert levels: NORMAL, WARNING, or CRITICAL.
Threshold Reference Table
Parameter Normal Warning Critical
Heart Rate 60–100 bpm 41–59 / 101–150 bpm ≤40 / ≥151 bpm
Systolic BP 90–140 mmHg 71–89 / 141–180 mmHg ≤70 / ≥181 mmHg
Diastolic BP 60–90 mmHg 41–59 / 91–120 mmHg ≤40 / ≥121 mmHg
Temperature 36.1–37.2 °C 35.0–36.0 / 37.3–39.5 °C <35.0 / >39.5 °C
SpO2 95–100 % 90–94 % <90 %
IEC 62304 Traceability
Software Unit: UNIT-VIT
Requirements covered: SWR-VIT-001 through SWR-VIT-007
Version
1.0.0
Date
2026-04-06
Author
vinu-engineer
Copyright
Medical Device Software — IEC 62304 Class B compliant. All rights reserved.
Definition in file vitals.h.
Enumeration Type Documentation
AlertLevel
enum AlertLevel
Classification of a vital sign reading relative to clinical norms.
The numeric ordering is intentional: ALERT_NORMAL < ALERT_WARNING < ALERT_CRITICAL, allowing comparisons such as if (level > ALERT_NORMAL). This ordering is relied upon by overall_alert_level().
Enumerator
ALERT_NORMAL
Reading within normal clinical range.
ALERT_WARNING
Reading outside normal range; clinician review recommended.
ALERT_CRITICAL
Reading at potentially life-threatening level; immediate intervention required.
Definition at line 46 of file vitals.h.
Function Documentation
alert_level_str()
const char * alert_level_str (AlertLevel level)
Convert an AlertLevel value to a human-readable string.
Parameters
[in] level The AlertLevel to convert.
Returns
One of: "NORMAL", "WARNING", "CRITICAL", or "UNKNOWN". Returned pointer is a string literal — caller must not free.
Requirement
SWR-VIT-007
Convert an AlertLevel value to a human-readable string.
Returns "UNKNOWN" for any value not in the enum to defend against undefined enum casts — important for IEC 62304 defensive coding.
Definition at line 135 of file vitals.c.
References ALERT_CRITICAL, ALERT_NORMAL, and ALERT_WARNING.
Referenced by patient_print_summary(), print_reading(), and update_dashboard().
bmi_category()
const char * bmi_category (float bmi)
Return the WHO BMI category string for a given BMI value.
BMI Range Category
< 18.5 Underweight
18.5 – 24.9 Normal weight
25.0 – 29.9 Overweight
≥ 30.0 Obese
< 0 Invalid
Parameters
[in] bmi BMI value as returned by calculate_bmi().
Returns
Null-terminated string literal (never NULL). Caller must not free.
Requirement
SWR-VIT-006
Return the WHO BMI category string for a given BMI value.
Uses half-open intervals consistent with WHO classification 2004.
Definition at line 121 of file vitals.c.
Referenced by monitor_patient(), monitor_second_patient(), paint_patient_bar(), and patient_print_summary().
calculate_bmi()
float calculate_bmi (float weight_kg, float height_m)
Calculate Body Mass Index (BMI) from weight and height.
Uses the standard formula: BMI = weight_kg / (height_m * height_m).
Parameters
[in] weight_kg Body weight in kilograms.
[in] height_m Height in metres. Must be > 0.
Returns
BMI value, or -1.0 if height_m is zero or negative.
Requirement
SWR-VIT-006
Calculate Body Mass Index (BMI) from weight and height.
BMI = weight_kg / (height_m^2). Returns -1.0 for invalid (zero or negative) height to allow callers to distinguish an error from a legitimate very-low BMI.
Definition at line 111 of file vitals.c.
Referenced by monitor_patient(), monitor_second_patient(), paint_patient_bar(), and patient_print_summary().
check_blood_pressure()
AlertLevel check_blood_pressure (int systolic, int diastolic)
Classify a blood pressure reading against clinical thresholds.
Both systolic and diastolic values are evaluated independently. The more severe of the two classifications is returned.
NORMAL: Systolic 90–140 mmHg AND diastolic 60–90 mmHg
WARNING: Systolic 71–89 / 141–180 mmHg OR diastolic 41–59 / 91–120 mmHg
CRITICAL: Systolic ≤70 / ≥181 mmHg OR diastolic ≤40 / ≥121 mmHg
Parameters
[in] systolic Systolic pressure in mmHg.
[in] diastolic Diastolic pressure in mmHg.
Returns
AlertLevel classification for the combined blood pressure reading.
Requirement
SWR-VIT-002
Classify a blood pressure reading against clinical thresholds.
Implements SWR-VIT-002 threshold logic. Critical thresholds are evaluated first (fail-safe ordering). If either systolic or diastolic is critical, CRITICAL is returned. If either is outside the normal range, WARNING is returned.
Definition at line 45 of file vitals.c.
References ALERT_CRITICAL, ALERT_NORMAL, and ALERT_WARNING.
Referenced by generate_alerts(), overall_alert_level(), paint_tiles(), patient_print_summary(), and print_reading().
check_heart_rate()
AlertLevel check_heart_rate (int bpm)
Classify a heart rate reading against clinical thresholds.
NORMAL: 60–100 bpm (inclusive)
WARNING: 41–59 bpm or 101–150 bpm
CRITICAL: ≤40 bpm or ≥151 bpm
Parameters
[in] bpm Heart rate in beats per minute. Negative values are treated as CRITICAL.
Returns
AlertLevel classification for the given heart rate.
Requirement
SWR-VIT-001
Classify a heart rate reading against clinical thresholds.
Implements SWR-VIT-001 threshold logic. Critical: bpm < 40 (severe bradycardia) or bpm > 150 (severe tachycardia). Warning: bpm < 60 or bpm > 100. Normal: 60 <= bpm <= 100.
Definition at line 31 of file vitals.c.
References ALERT_CRITICAL, ALERT_NORMAL, and ALERT_WARNING.
Referenced by generate_alerts(), overall_alert_level(), paint_tiles(), patient_print_summary(), and print_reading().
check_spo2()
AlertLevel check_spo2 (int spo2)
Classify a peripheral oxygen saturation reading.
NORMAL: 95–100 % (inclusive)
WARNING: 90–94 %
CRITICAL: <90 % (hypoxaemia)
Parameters
[in] spo2 SpO2 as a percentage (0–100). Values outside this range are treated as CRITICAL.
Returns
AlertLevel classification for the given SpO2 reading.
Requirement
SWR-VIT-004
Classify a peripheral oxygen saturation reading.
Implements SWR-VIT-004 threshold logic. <90% = hypoxaemia (CRITICAL). 90–94% = mild hypoxaemia (WARNING). 95–100% = normal saturation.
Definition at line 75 of file vitals.c.
References ALERT_CRITICAL, ALERT_NORMAL, and ALERT_WARNING.
Referenced by generate_alerts(), overall_alert_level(), paint_tiles(), patient_print_summary(), and print_reading().
check_temperature()
AlertLevel check_temperature (float temp_c)
Classify a body temperature reading against clinical thresholds.
NORMAL: 36.1–37.2 °C (inclusive)
WARNING: 35.0–36.0 °C or 37.3–39.5 °C
CRITICAL: <35.0 °C (hypothermia) or >39.5 °C (hyperpyrexia)
Parameters
[in] temp_c Body temperature in degrees Celsius.
Returns
AlertLevel classification for the given temperature.
Requirement
SWR-VIT-003
Classify a body temperature reading against clinical thresholds.
Implements SWR-VIT-003 threshold logic. <35.0 °C = hypothermia (CRITICAL). >39.5 °C = hyperpyrexia (CRITICAL). Values outside 36.1–37.2 but within critical bounds = WARNING.
Definition at line 61 of file vitals.c.
References ALERT_CRITICAL, ALERT_NORMAL, and ALERT_WARNING.
Referenced by generate_alerts(), overall_alert_level(), paint_tiles(), patient_print_summary(), and print_reading().
overall_alert_level()
AlertLevel overall_alert_level (const VitalSigns * vitals)
Return the highest alert level across all vital sign parameters.
Internally calls check_heart_rate(), check_blood_pressure(), check_temperature(), and check_spo2(), then returns the maximum value. This ensures that any single critical parameter elevates the overall patient status to CRITICAL regardless of other parameters.
Parameters
[in] vitals Pointer to a valid VitalSigns structure. Must not be NULL.
Returns
The highest AlertLevel among all four parameters.
Precondition
vitals != NULL
Requirement
SWR-VIT-005
Return the highest alert level across all vital sign parameters.
Implements SWR-VIT-005. Iterates all four checks and tracks the maximum. Uses a fixed-size array to avoid branch explosion and keep cyclomatic complexity low for IEC 62304 review.
Definition at line 88 of file vitals.c.
References ALERT_NORMAL, check_blood_pressure(), check_heart_rate(), check_spo2(), check_temperature(), VitalSigns::diastolic_bp, VitalSigns::heart_rate, VitalSigns::spo2, VitalSigns::systolic_bp, and VitalSigns::temperature.
Referenced by patient_current_status(), print_reading(), and update_dashboard().